/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package fr.squirrel.pdfview;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;

@Kroll.module(name="Pdfview", id="fr.squirrel.pdfview")
public class PdfviewModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "PdfviewModule";
	private static final boolean DBG = TiConfig.LOGD;

	public PdfviewModule()
	{
		super();
		
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
	}

}

